Repository WildCodeSchool/tours-php-2009-project2-mybooks, pull requests merged in 2020-11, with the labels that each got.

#13 Add Delete Functionality
  public/assets/css/style.css
  public/assets/images/cross.png
  public/assets/images/iconeplus.png
  public/assets/images/livrelu.png
  public/assets/images/livrenonlu.png
  public/assets/images/pen.png
  public/assets/images/presentation.jpg
  public/assets/images/trash.png
  public/assets/images/user.png
  src/Controller/BookController.php
  src/Model/BookManager.php
  src/View/book/_form.html.twig
  src/View/book/show.html.twig
Labels: Correction Done, reviewed

#14 View
  public/assets/css/style.css
  public/assets/images/booklu.png
  public/assets/images/booknonlu.png
  src/View/book/_form.html.twig
  src/View/book/add.html.twig
  src/View/book/edit.html.twig
  src/View/book/index.html.twig
  src/View/book/show.html.twig
  src/View/layout.html.twig
Labels: Correction Done, reviewed

#16 Paging
  config/config.php
  public/assets/css/style.css
  src/Controller/BookController.php
  src/Model/BookManager.php
  src/View/book/index.html.twig
Labels: reviewed

#20 Truncate title
  public/assets/css/style.css
  src/Model/Book.php
  src/View/book/index.html.twig
Labels: reviewed

#19 Keep form entries when there is an error
  src/Controller/BookController.php
  src/Model/Book.php
Labels: Correction Done, reviewed

#22 Css style
  public/assets/css/style.css
  public/assets/images/favicon.ico
  public/assets/images/favicon.png
  public/assets/images/iconeplus.png
  public/assets/images/iconplus.png
  public/assets/images/pen.png
  public/assets/images/read-book.png
  public/assets/images/search.png
  public/assets/images/trash.png
  public/assets/images/unread-book.png
  public/assets/images/user.png
  src/View/book/_form.html.twig
  src/View/book/index.html.twig
  src/View/book/show.html.twig
  src/View/layout.html.twig
Labels: reviewed

#18 Search bar functionality
  public/assets/css/style.css
  public/assets/images/magnifyingGlass.png
  src/Controller/BookController.php
  src/Model/BookManager.php
  src/View/book/index.html.twig
Labels: Correction Done, reviewed

#23 add css modifications in the index page
  public/assets/css/style.css
  src/View/book/index.html.twig
Labels: reviewed

#24 change of cssStyle on the edit and add page
  public/assets/css/style.css
  src/View/book/_form.html.twig
  src/View/book/add.html.twig
  src/View/book/edit.html.twig
Labels: Correction Done, reviewed

#27 Css rectification
  public/assets/css/style.css
  src/View/book/edit.html.twig
  src/View/book/index.html.twig
  src/View/book/show.html.twig
  src/View/layout.html.twig
Labels: Important, reviewed

#26 Legal mentions page modify
  public/assets/css/style.css
  src/Controller/BookController.php
  src/View/book/legalMentions.html.twig
  src/View/layout.html.twig
Labels: reviewed

#28 CSS modifications
  public/assets/css/style.css
  public/assets/images/booksPicture.jpg
  public/assets/images/user.png
  src/View/book/add.html.twig
  src/View/book/index.html.twig
Labels: reviewed

#39 ISBN
  public/assets/css/style.css
  src/Model/Book.php
  src/View/book/_form.html.twig
  src/View/book/index.html.twig
Labels: reviewed

#38 Add css modifications in index page
  public/assets/css/style.css
  src/View/book/index.html.twig
Labels: reviewed

#40 added friend exchange tracking with a 3-positions-toggle-button stati…
  mybooks.sql
  public/assets/css/togglebutton.css
  src/Controller/BookController.php
  src/Model/Book.php
  src/Model/BookManager.php
  src/View/book/_form.html.twig
  src/View/book/show.html.twig
  src/View/layout.html.twig
Labels: reviewed

#43 Delete user icon on the navbar
  public/assets/css/style.css
  public/assets/images/user.png
  src/View/layout.html.twig
Labels: reviewed

#44 PR master
  mybooks.sql
  public/assets/css/style.css
  public/assets/css/togglebutton.css
  public/assets/images/user.png
  src/Controller/BookController.php
  src/Model/Book.php
  src/Model/BookManager.php
  src/View/book/_form.html.twig
  src/View/book/index.html.twig
  src/View/book/show.html.twig
  src/View/layout.html.twig
Labels: reviewed

#45 change date
  src/View/book/show.html.twig
Labels: reviewed

#46 Last PR
  src/View/book/show.html.twig
Labels: reviewed
